module(
    name = "sonic-linux-kernel",
    version = "0.0.1",
)

bazel_dep(name = "platforms", version = "1.1.0")
bazel_dep(name = "rules_python", version = "1.7.0")
bazel_dep(name = "sonic-build-infra", version = "0.0.15-3a3d42932877e303385fd0b6503d1c413fc86bab", repo_name = "sonic_build_infra")

python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.toolchain(python_version = "3.13")

sources = use_extension("//tools/bazel:sources.bzl", "kernel_sources")
use_repo(sources, "kernel_debian", "kernel_dsc", "kernel_orig")
